version: '3'
services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "8001:5432"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db