defaults: &defaults
  email: example_user@example.com
  google_analytics_code: 123
  google_analytics_cookie_path:  ""
  src_maps_dir: 
  dst_maps_dir:
  mask_dir:
  tileindex_dir: 
  yahoo_app_id: "ascas"
  host: "localhost:3000"
  site_name: "MapWarper"
  id_key: ""
  id_secret: ""
  s3_db_access_key_id: ""
  s3_db_secret_access_key: ""
  s3_db_bucket_name: ""
  s3_db_bucket_path: ""
  s3_tiles_access_key_id: ""
  s3_tiles_secret_access_key: ""
  s3_tiles_bucket_name: ""
  s3_tiles_bucket_path: ""
  s3_tiles_max_zoom: "21"
  tilestache_path: ""

development:
  <<: *defaults

test:
  <<: *defaults
  email: test_user@example.com

production:
  <<: *defaults
  email: production_user@example.com
  src_maps_dir: "/var/etc/maps/src/"
  dst_maps_dir: "/var/etc/maps/dst/"
