defaults: &defaults
  email: example_user@example.com
  google_analytics_code: 123
  google_analytics_cookie_path:  ""
  src_maps_dir: 
  dst_maps_dir:
  mask_dir:
  tileindex_dir: 
  yahoo_app_id: "ascas"
  host: "localhost:3000"
  site_name: "MapWarper"
  omniauth_osm_key: "ABC"
  omniauth_osm_secret: "ABC"
  omniauth_twitter_key: "ABC"
  omniauth_twitter_secret: "ABC"
  omniauth_mediawiki_site: "https://commons.wikimedia.org"
  omniauth_mediawiki_key: "ABC"
  omniauth_mediawiki_secret: "ABC"
  omniauth_github_key: "ABC"
  omniauth_github_secret: "ABC"
  omniauth_google_key: "ABC"
  omniauth_google_secret: "ABC"
  omniauth_facebook_key: "ABC"
  omniauth_facebook_secret: "ABC"
  id_key: ""
  id_secret: ""
  s3_db_access_key_id: ""
  s3_db_secret_access_key: ""
  s3_db_bucket_name: ""
  s3_db_bucket_path: ""
  s3_tiles_access_key_id: ""
  s3_tiles_secret_access_key: ""
  s3_tiles_bucket_name: ""
  s3_tiles_bucket_path: ""
  s3_tiles_max_zoom: "21"
  tilestache_path: ""
  #throttling for destructive requests
  enable_throttling: true
  # throttle_limit is the number of requests and throttle_period is the number of seconds that the requests can occur
  throttle_limit: 30
  throttle_period: 60
  #throttle_delay is the number of seconds to add to the response on a throttled logged in call
  throttle_delay: 2
  

development:
  <<: *defaults

test:
  <<: *defaults
  email: test_user@example.com

production:
  <<: *defaults
  email: production_user@example.com
  src_maps_dir: "/var/etc/maps/src/"
  dst_maps_dir: "/var/etc/maps/dst/"
